FROM debian:12.8-slim
LABEL maintainer="RhavinX"

VOLUME ["/home/VRisingServer", "/data"]

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends apt-utils wget software-properties-common tzdata && \
    add-apt-repository main && \
    add-apt-repository contrib && \
    dpkg --add-architecture i386 && \
    apt-get update && apt-get upgrade -y
RUN useradd -m steam && cd /home/steam && \
    mkdir -pm755 /etc/apt/keyrings && \
    wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key && \
    wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/debian/dists/bookworm/winehq-bookworm.sources && \
    apt-get update -y && apt-get install -y --install-recommends winehq-stable && apt-get install -y --no-install-recommends winbind xvfb && \
    apt-get remove -y wget software-properties-common && apt-get clean -y && apt-get autoremove -y && apt purge '~c' -y && \    
    rm -rf /var/lib/apt/lists/*

COPY start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 27015/udp
EXPOSE 27016/udp

ENTRYPOINT [ "/start.sh" ]
