---
services:
  vrising:
    image: rhavinx/vrising-server
    labels:
      io.containers.autoupdate: image
    container_name: v-rising
    volumes:
      - /path/to/data:/data
    ports:
      - 27015:27015/udp
      - 27016:27016/udp
    restart: unless-stopped

